// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDytglzxB-1tQLfcm4B8SqbFMAzXO5ot7U',
    appId: '1:845855369372:web:f9a2f5b0670a6dc5bae559',
    messagingSenderId: '845855369372',
    projectId: 'projekaplikasi-c5b96',
    authDomain: 'projekaplikasi-c5b96.firebaseapp.com',
    storageBucket: 'projekaplikasi-c5b96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMjdRNuolbzBdHvwd2xbTLyy8bRYM9xkY',
    appId: '1:845855369372:android:7af8bbe5bea02f92bae559',
    messagingSenderId: '845855369372',
    projectId: 'projekaplikasi-c5b96',
    storageBucket: 'projekaplikasi-c5b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdY5e_myFWXRUR4lEi2bW239JLVn8pHfs',
    appId: '1:845855369372:ios:ff0a104ab05210f5bae559',
    messagingSenderId: '845855369372',
    projectId: 'projekaplikasi-c5b96',
    storageBucket: 'projekaplikasi-c5b96.appspot.com',
    iosBundleId: 'com.example.revisiYoga',
  );
}
